/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../../../routes/__root'
import { Route as PublicRouteImport } from './../../../routes/_public'
import { Route as AuthenticatedRouteImport } from './../../../routes/_authenticated'
import { Route as IndexRouteImport } from './../../../routes/index'
import { Route as PublicWelcomeRouteImport } from './../../../routes/_public/welcome'
import { Route as PublicSignInRouteImport } from './../../../routes/_public/sign-in'
import { Route as AuthenticatedSettingsRouteImport } from './../../../routes/_authenticated/settings'
import { Route as AuthenticatedProfileIndexRouteImport } from './../../../routes/_authenticated/profile/index'
import { Route as AuthenticatedProfileShippingAddressRouteImport } from './../../../routes/_authenticated/profile/shipping-address'
import { Route as AuthenticatedProfilePaymentMethodsRouteImport } from './../../../routes/_authenticated/profile/payment-methods'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicWelcomeRoute = PublicWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSignInRoute = PublicSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileShippingAddressRoute =
  AuthenticatedProfileShippingAddressRouteImport.update({
    id: '/profile/shipping-address',
    path: '/profile/shipping-address',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfilePaymentMethodsRoute =
  AuthenticatedProfilePaymentMethodsRouteImport.update({
    id: '/profile/payment-methods',
    path: '/profile/payment-methods',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sign-in': typeof PublicSignInRoute
  '/welcome': typeof PublicWelcomeRoute
  '/profile/payment-methods': typeof AuthenticatedProfilePaymentMethodsRoute
  '/profile/shipping-address': typeof AuthenticatedProfileShippingAddressRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sign-in': typeof PublicSignInRoute
  '/welcome': typeof PublicWelcomeRoute
  '/profile/payment-methods': typeof AuthenticatedProfilePaymentMethodsRoute
  '/profile/shipping-address': typeof AuthenticatedProfileShippingAddressRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_public/sign-in': typeof PublicSignInRoute
  '/_public/welcome': typeof PublicWelcomeRoute
  '/_authenticated/profile/payment-methods': typeof AuthenticatedProfilePaymentMethodsRoute
  '/_authenticated/profile/shipping-address': typeof AuthenticatedProfileShippingAddressRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/sign-in'
    | '/welcome'
    | '/profile/payment-methods'
    | '/profile/shipping-address'
    | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/sign-in'
    | '/welcome'
    | '/profile/payment-methods'
    | '/profile/shipping-address'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_public'
    | '/_authenticated/settings'
    | '/_public/sign-in'
    | '/_public/welcome'
    | '/_authenticated/profile/payment-methods'
    | '/_authenticated/profile/shipping-address'
    | '/_authenticated/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/welcome': {
      id: '/_public/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof PublicWelcomeRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/sign-in': {
      id: '/_public/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof PublicSignInRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/shipping-address': {
      id: '/_authenticated/profile/shipping-address'
      path: '/profile/shipping-address'
      fullPath: '/profile/shipping-address'
      preLoaderRoute: typeof AuthenticatedProfileShippingAddressRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/payment-methods': {
      id: '/_authenticated/profile/payment-methods'
      path: '/profile/payment-methods'
      fullPath: '/profile/payment-methods'
      preLoaderRoute: typeof AuthenticatedProfilePaymentMethodsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedProfilePaymentMethodsRoute: typeof AuthenticatedProfilePaymentMethodsRoute
  AuthenticatedProfileShippingAddressRoute: typeof AuthenticatedProfileShippingAddressRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedProfilePaymentMethodsRoute:
    AuthenticatedProfilePaymentMethodsRoute,
  AuthenticatedProfileShippingAddressRoute:
    AuthenticatedProfileShippingAddressRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicRouteChildren {
  PublicSignInRoute: typeof PublicSignInRoute
  PublicWelcomeRoute: typeof PublicWelcomeRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicSignInRoute: PublicSignInRoute,
  PublicWelcomeRoute: PublicWelcomeRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
