# pnpm workspace configuration
# Этот файл определяет структуру workspace для pnpm
# В данный момент проект не является монорепозиторием,
# но файл готов для будущего расширения

packages:
  # Основной проект
  - '.'

  # Будущие пакеты (раскомментировать при необходимости)
  # - 'packages/*'
  # - 'apps/*'
  # - 'libs/*'
