/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as LocaleLayoutRouteImport } from './routes/$locale/_layout'
import { Route as LocaleLayoutIndexRouteImport } from './routes/$locale/_layout/index'
import { Route as LocaleLayoutLoginRouteImport } from './routes/$locale/_layout/login'
import { Route as LocaleLayoutAboutRouteImport } from './routes/$locale/_layout/about'
import { Route as LocaleLayoutAuthenticatedRouteImport } from './routes/$locale/_layout/_authenticated'
import { Route as LocaleLayoutUsersIndexRouteImport } from './routes/$locale/_layout/users/index'
import { Route as LocaleLayoutUsersTableRouteImport } from './routes/$locale/_layout/users/table'
import { Route as LocaleLayoutUsersPlaceholderRouteImport } from './routes/$locale/_layout/users/placeholder'
import { Route as LocaleLayoutAuthenticatedSettingsRouteImport } from './routes/$locale/_layout/_authenticated/settings'
import { Route as LocaleLayoutAuthenticatedProfileRouteImport } from './routes/$locale/_layout/_authenticated/profile'
import { Route as LocaleLayoutAuthenticatedExamplesRouteImport } from './routes/$locale/_layout/_authenticated/examples'
import { Route as LocaleLayoutAuthenticatedDashboardRouteImport } from './routes/$locale/_layout/_authenticated/dashboard'
import { Route as LocaleLayoutAuthenticatedAdminRouteImport } from './routes/$locale/_layout/_authenticated/admin'
import { Route as LocaleLayoutAuthenticatedExamplesI18nRouteImport } from './routes/$locale/_layout/_authenticated/examples/i18n'

const LocaleRouteImport = createFileRoute('/$locale')()

const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleLayoutRoute = LocaleLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleLayoutIndexRoute = LocaleLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleLayoutRoute,
} as any)
const LocaleLayoutLoginRoute = LocaleLayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LocaleLayoutRoute,
} as any)
const LocaleLayoutAboutRoute = LocaleLayoutAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LocaleLayoutRoute,
} as any)
const LocaleLayoutAuthenticatedRoute =
  LocaleLayoutAuthenticatedRouteImport.update({
    id: '/_authenticated',
    getParentRoute: () => LocaleLayoutRoute,
  } as any)
const LocaleLayoutUsersIndexRoute = LocaleLayoutUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => LocaleLayoutRoute,
} as any)
const LocaleLayoutUsersTableRoute = LocaleLayoutUsersTableRouteImport.update({
  id: '/users/table',
  path: '/users/table',
  getParentRoute: () => LocaleLayoutRoute,
} as any)
const LocaleLayoutUsersPlaceholderRoute =
  LocaleLayoutUsersPlaceholderRouteImport.update({
    id: '/users/placeholder',
    path: '/users/placeholder',
    getParentRoute: () => LocaleLayoutRoute,
  } as any)
const LocaleLayoutAuthenticatedSettingsRoute =
  LocaleLayoutAuthenticatedSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => LocaleLayoutAuthenticatedRoute,
  } as any)
const LocaleLayoutAuthenticatedProfileRoute =
  LocaleLayoutAuthenticatedProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => LocaleLayoutAuthenticatedRoute,
  } as any)
const LocaleLayoutAuthenticatedExamplesRoute =
  LocaleLayoutAuthenticatedExamplesRouteImport.update({
    id: '/examples',
    path: '/examples',
    getParentRoute: () => LocaleLayoutAuthenticatedRoute,
  } as any)
const LocaleLayoutAuthenticatedDashboardRoute =
  LocaleLayoutAuthenticatedDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => LocaleLayoutAuthenticatedRoute,
  } as any)
const LocaleLayoutAuthenticatedAdminRoute =
  LocaleLayoutAuthenticatedAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => LocaleLayoutAuthenticatedRoute,
  } as any)
const LocaleLayoutAuthenticatedExamplesI18nRoute =
  LocaleLayoutAuthenticatedExamplesI18nRouteImport.update({
    id: '/i18n',
    path: '/i18n',
    getParentRoute: () => LocaleLayoutAuthenticatedExamplesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/$locale': typeof LocaleLayoutAuthenticatedRouteWithChildren
  '/$locale/about': typeof LocaleLayoutAboutRoute
  '/$locale/login': typeof LocaleLayoutLoginRoute
  '/$locale/': typeof LocaleLayoutIndexRoute
  '/$locale/admin': typeof LocaleLayoutAuthenticatedAdminRoute
  '/$locale/dashboard': typeof LocaleLayoutAuthenticatedDashboardRoute
  '/$locale/examples': typeof LocaleLayoutAuthenticatedExamplesRouteWithChildren
  '/$locale/profile': typeof LocaleLayoutAuthenticatedProfileRoute
  '/$locale/settings': typeof LocaleLayoutAuthenticatedSettingsRoute
  '/$locale/users/placeholder': typeof LocaleLayoutUsersPlaceholderRoute
  '/$locale/users/table': typeof LocaleLayoutUsersTableRoute
  '/$locale/users': typeof LocaleLayoutUsersIndexRoute
  '/$locale/examples/i18n': typeof LocaleLayoutAuthenticatedExamplesI18nRoute
}
export interface FileRoutesByTo {
  '/$locale': typeof LocaleLayoutIndexRoute
  '/$locale/about': typeof LocaleLayoutAboutRoute
  '/$locale/login': typeof LocaleLayoutLoginRoute
  '/$locale/admin': typeof LocaleLayoutAuthenticatedAdminRoute
  '/$locale/dashboard': typeof LocaleLayoutAuthenticatedDashboardRoute
  '/$locale/examples': typeof LocaleLayoutAuthenticatedExamplesRouteWithChildren
  '/$locale/profile': typeof LocaleLayoutAuthenticatedProfileRoute
  '/$locale/settings': typeof LocaleLayoutAuthenticatedSettingsRoute
  '/$locale/users/placeholder': typeof LocaleLayoutUsersPlaceholderRoute
  '/$locale/users/table': typeof LocaleLayoutUsersTableRoute
  '/$locale/users': typeof LocaleLayoutUsersIndexRoute
  '/$locale/examples/i18n': typeof LocaleLayoutAuthenticatedExamplesI18nRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/_layout': typeof LocaleLayoutRouteWithChildren
  '/$locale/_layout/_authenticated': typeof LocaleLayoutAuthenticatedRouteWithChildren
  '/$locale/_layout/about': typeof LocaleLayoutAboutRoute
  '/$locale/_layout/login': typeof LocaleLayoutLoginRoute
  '/$locale/_layout/': typeof LocaleLayoutIndexRoute
  '/$locale/_layout/_authenticated/admin': typeof LocaleLayoutAuthenticatedAdminRoute
  '/$locale/_layout/_authenticated/dashboard': typeof LocaleLayoutAuthenticatedDashboardRoute
  '/$locale/_layout/_authenticated/examples': typeof LocaleLayoutAuthenticatedExamplesRouteWithChildren
  '/$locale/_layout/_authenticated/profile': typeof LocaleLayoutAuthenticatedProfileRoute
  '/$locale/_layout/_authenticated/settings': typeof LocaleLayoutAuthenticatedSettingsRoute
  '/$locale/_layout/users/placeholder': typeof LocaleLayoutUsersPlaceholderRoute
  '/$locale/_layout/users/table': typeof LocaleLayoutUsersTableRoute
  '/$locale/_layout/users/': typeof LocaleLayoutUsersIndexRoute
  '/$locale/_layout/_authenticated/examples/i18n': typeof LocaleLayoutAuthenticatedExamplesI18nRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$locale'
    | '/$locale/about'
    | '/$locale/login'
    | '/$locale/'
    | '/$locale/admin'
    | '/$locale/dashboard'
    | '/$locale/examples'
    | '/$locale/profile'
    | '/$locale/settings'
    | '/$locale/users/placeholder'
    | '/$locale/users/table'
    | '/$locale/users'
    | '/$locale/examples/i18n'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$locale'
    | '/$locale/about'
    | '/$locale/login'
    | '/$locale/admin'
    | '/$locale/dashboard'
    | '/$locale/examples'
    | '/$locale/profile'
    | '/$locale/settings'
    | '/$locale/users/placeholder'
    | '/$locale/users/table'
    | '/$locale/users'
    | '/$locale/examples/i18n'
  id:
    | '__root__'
    | '/$locale'
    | '/$locale/_layout'
    | '/$locale/_layout/_authenticated'
    | '/$locale/_layout/about'
    | '/$locale/_layout/login'
    | '/$locale/_layout/'
    | '/$locale/_layout/_authenticated/admin'
    | '/$locale/_layout/_authenticated/dashboard'
    | '/$locale/_layout/_authenticated/examples'
    | '/$locale/_layout/_authenticated/profile'
    | '/$locale/_layout/_authenticated/settings'
    | '/$locale/_layout/users/placeholder'
    | '/$locale/_layout/users/table'
    | '/$locale/_layout/users/'
    | '/$locale/_layout/_authenticated/examples/i18n'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LocaleRoute: typeof LocaleRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/_layout': {
      id: '/$locale/_layout'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleLayoutRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/_layout/': {
      id: '/$locale/_layout/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleLayoutIndexRouteImport
      parentRoute: typeof LocaleLayoutRoute
    }
    '/$locale/_layout/login': {
      id: '/$locale/_layout/login'
      path: '/login'
      fullPath: '/$locale/login'
      preLoaderRoute: typeof LocaleLayoutLoginRouteImport
      parentRoute: typeof LocaleLayoutRoute
    }
    '/$locale/_layout/about': {
      id: '/$locale/_layout/about'
      path: '/about'
      fullPath: '/$locale/about'
      preLoaderRoute: typeof LocaleLayoutAboutRouteImport
      parentRoute: typeof LocaleLayoutRoute
    }
    '/$locale/_layout/_authenticated': {
      id: '/$locale/_layout/_authenticated'
      path: ''
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleLayoutAuthenticatedRouteImport
      parentRoute: typeof LocaleLayoutRoute
    }
    '/$locale/_layout/users/': {
      id: '/$locale/_layout/users/'
      path: '/users'
      fullPath: '/$locale/users'
      preLoaderRoute: typeof LocaleLayoutUsersIndexRouteImport
      parentRoute: typeof LocaleLayoutRoute
    }
    '/$locale/_layout/users/table': {
      id: '/$locale/_layout/users/table'
      path: '/users/table'
      fullPath: '/$locale/users/table'
      preLoaderRoute: typeof LocaleLayoutUsersTableRouteImport
      parentRoute: typeof LocaleLayoutRoute
    }
    '/$locale/_layout/users/placeholder': {
      id: '/$locale/_layout/users/placeholder'
      path: '/users/placeholder'
      fullPath: '/$locale/users/placeholder'
      preLoaderRoute: typeof LocaleLayoutUsersPlaceholderRouteImport
      parentRoute: typeof LocaleLayoutRoute
    }
    '/$locale/_layout/_authenticated/settings': {
      id: '/$locale/_layout/_authenticated/settings'
      path: '/settings'
      fullPath: '/$locale/settings'
      preLoaderRoute: typeof LocaleLayoutAuthenticatedSettingsRouteImport
      parentRoute: typeof LocaleLayoutAuthenticatedRoute
    }
    '/$locale/_layout/_authenticated/profile': {
      id: '/$locale/_layout/_authenticated/profile'
      path: '/profile'
      fullPath: '/$locale/profile'
      preLoaderRoute: typeof LocaleLayoutAuthenticatedProfileRouteImport
      parentRoute: typeof LocaleLayoutAuthenticatedRoute
    }
    '/$locale/_layout/_authenticated/examples': {
      id: '/$locale/_layout/_authenticated/examples'
      path: '/examples'
      fullPath: '/$locale/examples'
      preLoaderRoute: typeof LocaleLayoutAuthenticatedExamplesRouteImport
      parentRoute: typeof LocaleLayoutAuthenticatedRoute
    }
    '/$locale/_layout/_authenticated/dashboard': {
      id: '/$locale/_layout/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/$locale/dashboard'
      preLoaderRoute: typeof LocaleLayoutAuthenticatedDashboardRouteImport
      parentRoute: typeof LocaleLayoutAuthenticatedRoute
    }
    '/$locale/_layout/_authenticated/admin': {
      id: '/$locale/_layout/_authenticated/admin'
      path: '/admin'
      fullPath: '/$locale/admin'
      preLoaderRoute: typeof LocaleLayoutAuthenticatedAdminRouteImport
      parentRoute: typeof LocaleLayoutAuthenticatedRoute
    }
    '/$locale/_layout/_authenticated/examples/i18n': {
      id: '/$locale/_layout/_authenticated/examples/i18n'
      path: '/i18n'
      fullPath: '/$locale/examples/i18n'
      preLoaderRoute: typeof LocaleLayoutAuthenticatedExamplesI18nRouteImport
      parentRoute: typeof LocaleLayoutAuthenticatedExamplesRoute
    }
  }
}

interface LocaleLayoutAuthenticatedExamplesRouteChildren {
  LocaleLayoutAuthenticatedExamplesI18nRoute: typeof LocaleLayoutAuthenticatedExamplesI18nRoute
}

const LocaleLayoutAuthenticatedExamplesRouteChildren: LocaleLayoutAuthenticatedExamplesRouteChildren =
  {
    LocaleLayoutAuthenticatedExamplesI18nRoute:
      LocaleLayoutAuthenticatedExamplesI18nRoute,
  }

const LocaleLayoutAuthenticatedExamplesRouteWithChildren =
  LocaleLayoutAuthenticatedExamplesRoute._addFileChildren(
    LocaleLayoutAuthenticatedExamplesRouteChildren,
  )

interface LocaleLayoutAuthenticatedRouteChildren {
  LocaleLayoutAuthenticatedAdminRoute: typeof LocaleLayoutAuthenticatedAdminRoute
  LocaleLayoutAuthenticatedDashboardRoute: typeof LocaleLayoutAuthenticatedDashboardRoute
  LocaleLayoutAuthenticatedExamplesRoute: typeof LocaleLayoutAuthenticatedExamplesRouteWithChildren
  LocaleLayoutAuthenticatedProfileRoute: typeof LocaleLayoutAuthenticatedProfileRoute
  LocaleLayoutAuthenticatedSettingsRoute: typeof LocaleLayoutAuthenticatedSettingsRoute
}

const LocaleLayoutAuthenticatedRouteChildren: LocaleLayoutAuthenticatedRouteChildren =
  {
    LocaleLayoutAuthenticatedAdminRoute: LocaleLayoutAuthenticatedAdminRoute,
    LocaleLayoutAuthenticatedDashboardRoute:
      LocaleLayoutAuthenticatedDashboardRoute,
    LocaleLayoutAuthenticatedExamplesRoute:
      LocaleLayoutAuthenticatedExamplesRouteWithChildren,
    LocaleLayoutAuthenticatedProfileRoute:
      LocaleLayoutAuthenticatedProfileRoute,
    LocaleLayoutAuthenticatedSettingsRoute:
      LocaleLayoutAuthenticatedSettingsRoute,
  }

const LocaleLayoutAuthenticatedRouteWithChildren =
  LocaleLayoutAuthenticatedRoute._addFileChildren(
    LocaleLayoutAuthenticatedRouteChildren,
  )

interface LocaleLayoutRouteChildren {
  LocaleLayoutAuthenticatedRoute: typeof LocaleLayoutAuthenticatedRouteWithChildren
  LocaleLayoutAboutRoute: typeof LocaleLayoutAboutRoute
  LocaleLayoutLoginRoute: typeof LocaleLayoutLoginRoute
  LocaleLayoutIndexRoute: typeof LocaleLayoutIndexRoute
  LocaleLayoutUsersPlaceholderRoute: typeof LocaleLayoutUsersPlaceholderRoute
  LocaleLayoutUsersTableRoute: typeof LocaleLayoutUsersTableRoute
  LocaleLayoutUsersIndexRoute: typeof LocaleLayoutUsersIndexRoute
}

const LocaleLayoutRouteChildren: LocaleLayoutRouteChildren = {
  LocaleLayoutAuthenticatedRoute: LocaleLayoutAuthenticatedRouteWithChildren,
  LocaleLayoutAboutRoute: LocaleLayoutAboutRoute,
  LocaleLayoutLoginRoute: LocaleLayoutLoginRoute,
  LocaleLayoutIndexRoute: LocaleLayoutIndexRoute,
  LocaleLayoutUsersPlaceholderRoute: LocaleLayoutUsersPlaceholderRoute,
  LocaleLayoutUsersTableRoute: LocaleLayoutUsersTableRoute,
  LocaleLayoutUsersIndexRoute: LocaleLayoutUsersIndexRoute,
}

const LocaleLayoutRouteWithChildren = LocaleLayoutRoute._addFileChildren(
  LocaleLayoutRouteChildren,
)

interface LocaleRouteChildren {
  LocaleLayoutRoute: typeof LocaleLayoutRouteWithChildren
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleLayoutRoute: LocaleLayoutRouteWithChildren,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LocaleRoute: LocaleRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
